#tight aggressive hard-coded

slownik = {
    "AKs" : "very strong",
    "AAo" : "very strong",
    "KKo" : "very strong",
    "QQo" : "very strong",
    "AKo" : "very strong",

    "JJo" : "strong",
    "TTo" : "strong",
    "99o" : "strong",

    "AQs" : "strong", 
    "AQo" : "strong", 

    "AJs" : "strong",

    "AJs" : "med",
    "ATs" : "med", 
    "KQs" : "med", 
    "AJo" : "med",
    "ATo" : "med", 
    "KQo" : "med", 

    "88o" : "speculative",
    "77o" : "speculative",
    "66o" : "speculative",
    "55o" : "speculative", 
    "44o" : "speculative",
    "33o" : "speculative",
    "22o" : "speculative",
    "KJs" : "speculative",
    "KTs" : "speculative", 
    "QJs" : "speculative", 
    "QTs" : "speculative",
    "JTs" : "speculative",
    "T9s" : "speculative",

    "KJo" : "mixed",
    "KTo" : "mixed",
    "QJo" : "mixed",
    "QTo" : "mixed", 
    "JTo" : "mixed",

    "A9s" : "mixed",
    "A8s" : "mixed",
    "A7s" : "mixed",
    "A6s" : "mixed",
    "A5s" : "mixed",
    "A4s" : "mixed",
    "A3s" : "mixed",
    "A2s" : "mixed",
    "K9s" : "mixed",
    "K8s" : "mixed",
    "K7s" : "mixed",
    "K6s" : "mixed",
    "K5s" : "mixed",
    "K4s" : "mixed",
    "K3s" : "mixed",
    "K2s" : "mixed",
    "Q9s" : "mixed",
    "Q8s" : "mixed",
    "Q7s" : "mixed",
    "Q6s" : "mixed",
    "Q5s" : "mixed",
    "Q4s" : "mixed",
    "Q3s" : "mixed",
    "Q2s" : "mixed",
    "J9s" : "mixed",
    "J8s" : "mixed",
    "J7s" : "mixed",
    "J6s" : "mixed",
    "J5s" : "mixed",
    "J4s" : "mixed",
    "J3s" : "mixed",
    "J2s" : "mixed",
    "T9s" : "mixed",
    "T8s" : "mixed",
    "T7s" : "mixed",
    "T6s" : "mixed",
    "T5s" : "mixed",
    "T4s" : "mixed",
    "T3s" : "mixed",
    "T2s" : "mixed",

    "98s" : "mixed",
    "97s" : "mixed",
    "96s" : "mixed",
    "95s" : "mixed",
    "94s" : "mixed",
    "93s" : "mixed",
    "92s" : "mixed",
    "89s" : "mixed",
    "87s" : "mixed",
    "86s" : "mixed",
    "85s" : "mixed",
    "84s" : "mixed",
    "83s" : "mixed",
    "82s" : "mixed",
    "79s" : "mixed",
    "78s" : "mixed",
    "76s" : "mixed",
    "75s" : "mixed",
    "74s" : "mixed",
    "73s" : "mixed",
    "72s" : "mixed",
    "69s" : "mixed",
    "68s" : "mixed",
    "67s" : "mixed",
    "65s" : "mixed",
    "64s" : "mixed",
    "63s" : "mixed",
    "62s" : "mixed",
    "59s" : "mixed",
    "58s" : "mixed",
    "57s" : "mixed",
    "56s" : "mixed",
    "54s" : "mixed",
    "53s" : "mixed",
    "52s" : "mixed",
    "49s" : "mixed",
    "48s" : "mixed",
    "47s" : "mixed",
    "46s" : "mixed",
    "45s" : "mixed",
    "43s" : "mixed",
    "42s" : "mixed",
    "39s" : "mixed",
    "38s" : "mixed",
    "37s" : "mixed",
    "36s" : "mixed",
    "35s" : "mixed",
    "34s" : "mixed",
    "32s" : "mixed",
    "29s" : "mixed",
    "28s" : "mixed",
    "27s" : "mixed",
    "26s" : "mixed",
    "25s" : "mixed",
    "24s" : "mixed",
    "23s" : "mixed"}

def card_format_so(card1, card2):
    if card1[0] == card2[0]:
        return card1[1] + card2[1] + "s"
    else:
        return card1[1] + card2[1] + "o"
    
def card_power(card1, card2):
    cards = card_format_so(card1, card2)
    if cards in slownik:
        return slownik[cards]
    else:
        return "trash"